query GetTransactions {
	getTransactions {
		__typename

		id
		date
		amount
		beneficiary
		description

		... on PaymentTransaction {
			jar {
				id
				name
			}
			account {
				id
				name
			}
			direction
		}
	}
}

mutation CreatePaymentTransaction($req: CreatePaymentTransaction!) {
	createPaymentTransaction(req: $req) {
		id
		date
		amount
		beneficiary
		description
		direction
	}
}

mutation UpdatePaymentTransaction($id: ID!, $req: CreatePaymentTransaction!) {
	updatePaymentTransaction(id: $id, req: $req) {
		id
		date
		amount
		beneficiary
		description
		direction
	}
}

mutation DeleteTransaction($id: ID!) {
	deleteTransaction(id: $id)
}
